### ISSUE TITLE
Add Russian Translation

### ISSUE THREAD

**Issue by Qussth** [golang-standards/project-layout#108]
Hi everyone! I`ve done translating README to Russian, how can I create a merge request or something?

**Comment by egorzot** [comment]
@Qussth сделай пул реквест со своими измененями, посотри пример в списке пул реквестов преокта.

**Comment by Qussth** [comment]
Made pull request for russian translation https://github.com/golang-standards/project-layout/pull/116

**Comment by kcq** [comment]
PR merged... closing
