### ISSUE TITLE
Dockerfile for standard project layout

### ISSUE THREAD

**Issue by dunods** [golang-standards/project-layout#14]
Does anyone have sample of dockerfile for standard project layout for the multi stage build ?

please help

**Comment by kcq** [comment]
Can you share a bit more content? What are you trying to do?

**Comment by astericky** [comment]
I can help with this potentially. I worked on dockerizing multiple go projects. Let me try to get a pull req going tonight when I get home.

**Comment by kcq** [comment]
Thank you for volunteering to help! The template repo would be a good place for it: https://github.com/golang-standards/project-template The `/build/package/docker` directory is a good place for it.

Do you have any existing Dockerfile samples?

**Comment by dunods** [comment]
i finally manage to build it and have already create pull request for the package.

here are the sample 
# Start from a Debian image with the latest version of Go installed
# and a workspace (GOPATH) configured at /go.
FROM golang:latest as builder
RUN go version

# Copy the local package files to the container's workspace.
ADD . /go/src/gitlab.com/{OWNER_NAME}/{PACKAGE_NAME}

# Copy the code from the host and compile it
WORKDIR $GOPATH/src/gitlab.com/{OWNER_NAME}/{PACKAGE_NAME}

# Build the output command inside the container.
# (You may fetch or manage dependencies here,
# either manually or with a tool like "godep".)
RUN set -x && \
    go get github.com/golang/dep/cmd/dep && \
    dep ensure -v
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o cmd/{PACKAGE_NAME} $GOPATH/src/gitlab.com/{OWNER_NAME}/{PACKAGE_NAME}/cmd

# Stage 2 (to create a downsized "container executable", ~7MB)

# If you need SSL certificates for HTTPS, replace `FROM SCRATCH` with:
#
#   FROM alpine:3.7
#   RUN apk --no-cache add ca-certificates
#
FROM scratch
WORKDIR /root/
COPY --from=builder /go/src/gitlab.com/{OWNER_NAME}/{PACKAGE_NAME}/cmd/{PACKAGE_NAME} .
#COPY --from=builder /go/src/gitlab.com/{OWNER_NAME}/{PACKAGE_NAME}/configs/json/db.json /configs/json/db.json
#COPY --from=builder /go/src/gitlab.com/{OWNER_NAME}/{PACKAGE_NAME}/configs/json/server.json /configs/json/server.json
#RUN ls
# Run the output command by default when the container starts.
CMD ["./{PACKAGE_NAME}"]

# Document that the service listens on port 8080.
EXPOSE 8080
