### ISSUE TITLE
Rename of this org?

### ISSUE THREAD

**Issue by WolfMcPhearson** [golang-standards/project-layout#173]
Is this an official Go standard org, owned by the same people that own github.com/golang?  If not, it appears it causes confusion, and should be renamed.  Seems like it might violate the spirit of the Acceptable Use Policy section 3:

> [impersonates any person or entity](https://docs.github.com/en/github/site-policy/github-impersonation), including any of our employees or representatives, including through false association with GitHub, or by fraudulently misrepresenting your identity or site's purpose

specifically the "fraudulently misrepresenting your identity or **_site's purpose_**.   And if you click on the link for impersonation you will see "Using a deceptively similar username, **_organization name_**, or other namespace," which I think accurately reflects the confusion with this org name, if in fact it is not owned by the golang devs.

While analogies are fret with issues, we can imagine the same confusion would exist in similar circumstances.  For example, if some people, not affiliated with the creators of the respective languages, created an org named python-standards, csharp-standards, java-standards, or any other name claiming to be standards for a particular programming language or well-known framework., such as dotnet-standards.   Someone apparently created a rust-standards org, but there are no public repos.  Hopefully this goes away also, unless owned by the rust folk of course.  However, like this repo that has a _disclaimer_ that it is not official, it has a subtitle of "Unofficial Rust Standards," so it is also likely not approved by the rust team, and will also likely create confusion if anything ever is released public.

I understand the impact of renaming an org or changing the import path of a repo/module, but it appears that the public repos in this org are more documentation and not meant to be imported into any Go program directly.  Therefore, the impact would be positive, "breaking" existing URLs that point to these misleadingly named org repos.

Can the golang-standards org be renamed, assuming it is not owned, sponsored, or run by the go developers?

**Comment by OneCricketeer** [comment]
Duplicates #52

**Comment by kcq** [comment]
this has been discussed already
