### ISSUE TITLE
Golang has the concept of models/services/repo? 

### ISSUE THREAD

**Issue by brunogbarros** [golang-standards/project-layout#184]
Can I use models/services/repositories folder inside /internal? 
I mean, I know we can use, but theres a golang way of using this?
I know this is a concept from other languages such Java (which is mine, and my team background) , but where should we put structs that looks like a model?

**Comment by Arsen6331** [comment]
See #117

**Comment by brunogbarros** [comment]
Thanks @Arsen6331 I'll take a look at this thread. I am not close this issue now, but if I agree if the thread I come back and close it, is it ok?

**Comment by brunogbarros** [comment]
Closing this issue, the thread @Arsen6331 shared was useful (thank u), but lead me to #52 which I agree. We all know this org is not official, but it looks solid and a lot of people recommend to new golang developers (not metion the SEO/google search), which I think can lead us (me included) the wrong path. This repository organization feels like structuring java for golang and thats why I created this issue, because it feels wrong.
