### ISSUE TITLE
This organization should be renamed with a note in the README

### ISSUE THREAD

**Issue by Elara6331** [golang-standards/project-layout#185]
Numerous people have created issues that describe the reasoning for this. The main one being #117, created by Russ Cox, the number one contributor to https://github.com/golang/go.

This repository represents your opinion, @kcq, and solely your opinion. To represent this as in any way standard, best practices, recommended, or anything else that would make it seem like more than just your preference is misleading and harmful to the entire Go community, and you should be ashamed for having done so without any discussion with the community you claim to represent.

I believe you should rename this repository to `my-golang-preferences` with a note at the top of the README with ":warning:" next to it that reads "This repository is IN NO WAY STANDARD. It represents my own preferences and ONLY my preferences. Most people in the Go community disagree with my preferences, so do not use this for your project unless you have evaluated all other layouts, such as those used for the standard library, and come to the conclusion that you like this one more!"

The failure to do so would suggest that you are acting in bad faith against the community.

**Comment by kcq** [comment]
@Arsen6331 thank you for being civil expressing your opinion! You happen to have a very narrow definition of "standards" and that's ok. The repo is not presented as an official standard from the Go team in any way and there's an explicit disclaimer providing sufficient context (in bold text at the very top of the readme).

**Comment by jm96441n** [comment]
Our of curiosity, why name the org `golang-standards` if it's definitely not a standard?

**Comment by brunogbarros** [comment]
Hello again @Arsen6331 , cant agree more. I was right now reading the issue #52 which has the same purpose. I 100% agree that this repo shouldn't be called "standard" and in the README the first sentence is "we are not official standard", this really lead people to mislead info.

**Comment by brunogbarros** [comment]
> @Arsen6331 thank you for being civil expressing your opinion! You happen to have a very narrow definition of "standards" and that's ok. The repo is not presented as an official standard from the Go team in any way and there's an explicit disclaimer providing sufficient context (in bold text at the very top of the readme).

Why to stay with a name thats creating more confusion than helping the community? Theres no reason to use the word 'standard' without being a official one, why not call this repository golang-patterns or something that community knows that can be unofficial.

**Comment by soypat** [comment]
I do appreciate the notes in the README! Thanks for going through the work of putting them in there- though I noticed the project description reads `Standard Go Project Layout`. This is the first thing people usually see and surely has an effect on perception when proceeding to see the project structure.

Maybe adding a ":warning: _unofficial_ :warning:" text could ease the misunderstandings people have when it comes to this repo?

**Comment by kcq** [comment]
Totally fine to have a different opinion and prefer something else. I hear you and respect you for sharing your option. Neither the repo name nor the repo description claims it represents the official standard or some kind of official standard.
