### ISSUE TITLE
Minio no longer uses /pkg in the project layout

### ISSUE THREAD

**Issue by Paulo-Lopes-Estevao** [golang-standards/project-layout#214]
Minio no longer uses /pkg in the default project layout.
This is also causing problems when making a request to the address https://github.com/minio/minio/tree/master/pkg

**Comment by amnonbc** [comment]
This repo does contain a lot of questionable advice.

So I would advise anyone looking for a starting point for project layout to look instead at the examples published by the Go team.

https://go.googlesource.com/example/+/refs/heads/master

**Comment by kcq** [comment]
Nice catch! They transitioned to the `internal` directory pattern :-)
