### ISSUE TITLE
Regarding the description of the deprecated tool golint

### ISSUE THREAD

**Issue by aqyuki** [golang-standards/project-layout#224]
Currently `golint` is a deprecated tool and it is recommended that other linters be used. However, there are several references in the **README** that recommend the use of golint. We should discuss changing this statement.

**Comment by kcq** [comment]
@aqyuki good idea to update the README to use the most common lint tool

**Comment by aqyuki** [comment]
I would like to change to recommend `staticcheck` instead of  `golint`

**Comment by kcq** [comment]
closing because the golint is now replaced with the staticcheck reference
