### ISSUE TITLE
Official layout documentation

### ISSUE THREAD

**Issue by lzambarda** [golang-standards/project-layout#234]
Hi there, Go Team has finally released their guidelines on how to structure a go module. The link is here: https://go.dev/doc/modules/layout
I believe that perhaps this repo should now at least mention the existence of a true goland standard?

**Comment by ahmetb** [comment]
+1 this repo's readme should start with a big 

> **Important**
> Go project now offers an official layout recommendation.

Let's see :)

**Comment by HeavenZhi** [comment]
Oh!! Thanks for mentioning this and provided a link to it, I used to get annoyed with the way the Go project was laid out. Now that the Go team has published a formal project layout standard, I'll use it as a primary reference.

**Comment by kcq** [comment]
Definitely good idea to add.
