### ISSUE TITLE
void

### ISSUE THREAD

**Issue by lazaridiscom** [golang-standards/project-layout#28]

**Comment by kcq** [comment]
@lazaridiscom I understand where you are coming from. There are benefits in keeping the code separate from non-code. It's not Go's way of doing things though. Definitely feel free to use the `code` folder if it makes sense for your projects. Things get pretty interesting with large projects and especially with mono repos :-)

**Comment by TimSatke** [comment]
IMO, when you use a `code` folder, you can use the `pkg` folder for that.

**Comment by lazaridiscom** [comment]
> Things get pretty interesting with large projects and especially with mono repos

Many go projects are not that (large mono-repo projects), but ordinary projects. There, the code-folder is simply a organizational "must" (e.g. "Standard-Procedure").


> IMO, when you use a code folder, you can use the pkg folder for that.

this *could* be ok (and should possibly be suggested in the "golang-standards".

But suggesting "If you can help yourself try not to adopt this Java pattern. You really don't want your Go code or Go projects to look like Java :-)" is pure amateurish nonsense, and leads to messy projects.

.
