### ISSUE TITLE
Not clear where to put files containing secrets

### ISSUE THREAD

**Issue by ndabAP** [golang-standards/project-layout#30]
I've a [service account file](https://cloud.google.com/iam/docs/creating-managing-service-account-keys) generated by Google which contains (secret) keys. I can't conclude from the current setup where to put these into.

My first idea was `configs`. But for me, `configs` can be public.

**Comment by ilazakis** [comment]
Public or not, committing any type of secret in source control is a bad practice/idea. 

Even private repos can accidentally become public, wrecking havoc in operations if secrets were included for at least a few days, if you’re lucky to find out early enough.

Secrets should be dynamically resolved using services specifically solving that kind of “config/secrets discovery” problem.

That is, I don’t think this is a Go project layout problem specifically.

**Comment by ndabAP** [comment]
>Public or not, committing any type of secret in source control is a bad practice/idea.

Totally agree. I don't want to commit them. My idea was to store an example file like `*.json.dist` to signal another developer to place their personal secret file here.

**Comment by ndabAP** [comment]
After some discussion at [Reddit](https://www.reddit.com/r/golang/comments/cl1ftn/where_do_you_put_secret_files_into/), the best solution for me would be using an `.env` file:

**.env**
```
SECRECT_FILE_LOCATION="~/.config/app/secret.json"
```

**Comment by ilazakis** [comment]
Ah, yes, of course; assuming the file itself is not committed, that would be the preferable [option](https://12factor.net/config) 👍

**Comment by ndabAP** [comment]
Thanks a lot for taking the time!

**Comment by kcq** [comment]
whatever the name/place is it's good to have it in the .gitignore file (if it's a default path/name then a template .gitignore file can be used :-))
