### ISSUE TITLE
Best practice for file server path name? /files or /static or what else?

### ISSUE THREAD

**Issue by frederikhors** [golang-standards/project-layout#37]
Is there a best practice in GO for file server path name?

I can imagine "`/files`" or "`/static`".

What do you think?

**Comment by kcq** [comment]
@frederikhors it all depends :) There's no hard best practice and a lot of it depends on the context (in some cases it has little to do with Go and it's influenced by other components you are using and the type of data you are serving :-)). For example, if your repo includes your project's website its static files can go under `/website/assets` or `/website/static`. If it's the static files for your go-based web app then the files can go under `/web/static` or `/web/assets`. If your web app is not an SPA that you can still use those `/web` subdirectories or you can simply put all your static web files in the root `/static` directory. If you have more than one executables (e.g., when you have `/cmd/app-one` and `/cmd/app-two`) and if the executables serve different files then it's good to mirror what you have in `/cmd` under `/static`, so you'd have `/static/app-one` and `/static/app-two`.
