### ISSUE TITLE
fu** stupid project !

### ISSUE THREAD

**Issue by loveship00** [golang-standards/project-layout#40]

**Comment by kcq** [comment]
Not cool and not professional :-(

**Comment by Ariemeth** [comment]
I disagree with this repo, but this issue is just wrong @loveship00

**Comment by dsoprea** [comment]
Feel free to report them to GH.

https://github.com/contact/report-content

**Comment by frederikhors** [comment]
Feel free to report them to GH.

https://github.com/contact/report-content
