### ISSUE TITLE
No src folder although the official guide tells to?

### ISSUE THREAD

**Issue by cwansart** [golang-standards/project-layout#48]
Hey,

I was wonderin what you think about the official Go documentation, which recommends creating a `src` folder, whereas you tell us not to.

Here's the link: https://golang.org/doc/code.html

**Comment by gsom95** [comment]
Official Go documentation specifies **workspace** hierarchy whereas here it's about **project** hierarchy. That is your project directory is inside workspace directory.
Read this [part](https://github.com/golang-standards/project-layout#src) carefully.
> Don't confuse the project level /src directory with the /src directory Go uses for its workspaces as described in How to Write Go Code. The $GOPATH environment variable points to your (current) workspace (by default it points to $HOME/go on non-windows systems). This workspace includes the top level /pkg, /bin and /src directories. Your actual project ends up being a sub-directory under /src, so if you have the /src directory in your project the project path will look like this: /some/path/to/workspace/src/your_project/src/your_code.go.

**Comment by cwansart** [comment]
Okay thanks. I may have misunderstood that. Thanks for pointing out.
