### ISSUE TITLE
Golang API: Code from other languages ?

### ISSUE THREAD

**Issue by lerenn** [golang-standards/project-layout#92]
Hello,

I'm currently developing a RESTful API in Go and I'm using this helpful layout to organize my project.
However, I'm more comfortable in placing other language client code (by example, Python) to access this API into the main project in order to keep consistency between version. 

So I got two questions :
 - Is this really a good idea or should I separate the Golang project from its client in other languages ?
 - If this is not a bad idea, in which folder should I place this code ?

Thank you very much :smiley:

**Comment by Deichindianer** [comment]
Hi ya,

Just putting my thoughts here on that :)

I'd say it could live under something like `examples/api-client/python/...` but only if it's a small example.
For a full client library package in a different language I'd put it in a separate repository, makes your life much easier with:

* Keeping release versions in order
* Testing of your client side code
* Different CI pipeline tooling for different languages

Overall the more robust approach will probably just be a separate repository to make keep your pipelines fairly straight forward and easier to maintain.

Hope this helps and I by no means claim that this is any sort of truth, just my thoughts on the topic.

Cheers!

**Comment by lerenn** [comment]
Agreed. I think in my situation it's better to go for a separate repository, but if I had to put it inside my repo, I would do what you suggested !

Thanks :+1:
