### ISSUE TITLE
Using docker while every service in cmd directory is another image

### ISSUE THREAD

**Issue by gbaranski** [golang-standards/project-layout#94]
Hello, I'm struggling with building each `/cmd/*` separately, not as a single image, and I'm not able to build it when context directory doesn't have go.mod itself. Have anyone managed to use Docker with this layout?

**Comment by flowchartsman** [comment]
I do this.

I have a base dockerfile which copies all source files into itself. Then each cmd uses this as a build image, and it builds itself in that container and copies the resulting binary to scratch.

**/projectroot/Dockerfile**
```
FROM golang:alpine
RUN apk --no-cache add ca-certificates git openssh curl
# ADD certs/mycert.crt /usr/local/share/ca-certificates/mycert.crt
# RUN chmod 0600 /usr/local/share/ca-certificates/mycert.crt && update-ca-certificates
# RUN go env -w GOPRIVATE=my.private.repo/*

# ADD gitconfig /root/.gitconfig
# ADD ssh /root/.ssh
# RUN chmod 0600 /root/.ssh/id_rsa /root/.ssh/config && \
#     chmod 0644 /root/.ssh/id_rsa.pub

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
```

**/cmd/foo/Dockerfile**
```
# syntax = docker/dockerfile:1-experimental
FROM whatever/yourproj:base as build
# Remove if you DO need it
ENV CGO_ENABLED=0
RUN --mount=type=cache,target=/root/.cache/go-build \
    cd /build/cmd/apisrv && go build

FROM scratch
COPY --from=build /build/cmd/apisrv/apisrv /
ENTRYPOINT ["/apisrv"]
```

Doing it this way _does_ mean you will need to get explicit in your `.dockerignore`, since you really only want Go files in your base image and docker still does not support whitelisting properly, no matter what you might read online.  Mine is something like this:

```
**/Dockerfile
**/*.md
**/*.sh
**/*.code-workspace
**/.DS_Store
**/*.exe

**/.git
.gitignore
.dockerignore
.vscode

magefile.go
```

That said, I do not recommend you use most of the recommendations in this repository, and instead stick with a simplified layout like mentioned here: https://eli.thegreenplace.net/2019/simple-go-project-layout-with-modules/

**Comment by kcq** [comment]
> Hello, I'm struggling with building each `/cmd/*` separately, not as a single image, and I'm not able to build it when context directory doesn't have go.mod itself. Have anyone managed to use Docker with this layout?

@gbaranski  Do you mind sharing a bit more about your build setup? 

It sounds like your app subdirectories under `/cmd` each have their own Dockerfile and you try building each app by going to their subdirectory (e.g., `/cmd/your_app_one`) and running `docker build -t your_app_image_name .`.

One option is to run each `docker build` command from the project root (or you can set the context directory explicitly, so it points to the project root directory) and then you can use the `-f` flag to point to the application specific Dockerfile (e.g., `docker build -f cmd/your_app_one/Dockerfile .`). 

If you are trying to keep the application subdirectories under `/cmd` clean (so it's code only) and you keep your app Dockerfiles under `/build` then your `docker build` command might look like this: `docker build -f build/package/docker/Dockerfile.your_app_one .`

Note that your app Dockerfile can even live outside of the context directory you pass to `docker build`, which provides more flexibility in terms of how you structure your project directory.

Quick question... are you using multi-stage builds for your application Docker images or are you trying to keep things simple and have regular Dockerfiles where you build and run your app all in one place?

**Comment by gbaranski** [comment]
> > Hello, I'm struggling with building each `/cmd/*` separately, not as a single image, and I'm not able to build it when context directory doesn't have go.mod itself. Have anyone managed to use Docker with this layout?
> 
> @gbaranski Do you mind sharing a bit more about your build setup?
> 
> It sounds like your app subdirectories under `/cmd` each have their own Dockerfile and you try building each app by going to their subdirectory (e.g., `/cmd/your_app_one`) and running `docker build -t your_app_image_name .`.
> 
> One option is to run each `docker build` command from the project root (or you can set the context directory explicitly, so it points to the project root directory) and then you can use the `-f` flag to point to the application specific Dockerfile (e.g., `docker build -f cmd/your_app_one/Dockerfile .`).
> 
> If you are trying to keep the application subdirectories under `/cmd` clean (so it's code only) and you keep your app Dockerfiles under `/build` then your `docker build` command might look like this: `docker build -f build/package/docker/Dockerfile.your_app_one .`
> 
> Note that your app Dockerfile can even live outside of the context directory you pass to `docker build`, which provides more flexibility in terms of how you structure your project directory.
> 
> Quick question... are you using multi-stage builds for your application Docker images or are you trying to keep things simple and have regular Dockerfiles where you build and run your app all in one place?

Hi, thanks for reply, that's how the project look like: https://github.com/gbaranski/houseflow/. Yes I'm using multi staged builds, the problem is that even if every app under cmd folder have the same build process, Dockerfile must be separated because it's context has to be on project root, so it is required to change directory to this cmd/app_name, however maybe it's possible to do using Dockerfile build flags but I havent look into it.

**Comment by flowchartsman** [comment]
If your problem is that your `/cmd` files depend on things in the project root, you can create a root image which has all of the files in it and build your cmd in a second-stage image built from that.  If your problem is that you have to download modules or compile each time, consider using named [Buildkit cache mounts](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#run---mounttypecache) so that they can be shared.

**Comment by kcq** [comment]
> Hi, thanks for reply, that's how the project look like: https://github.com/gbaranski/houseflow/. Yes I'm using multi staged builds, the problem is that even if every app under cmd folder have the same build process, Dockerfile must be separated because it's context has to be on project root, so it is required to change directory to this cmd/app_name, however maybe it's possible to do using Dockerfile build flags but I havent looked into it.

@gbaranski Sweet project! When do you feel it's going to be ready for use :-) Thanks for sharing... I'll try a few things to see how far I can get, so there's something specific we can reference in the discussion.

**Comment by gbaranski** [comment]
> you can create a root image which has all of the files in it and build your cmd in a second-stage image built from that. 

That's great idea. thanks.

I think the thing that I can also do is making common Dockerfile which will have context on the cmd/name/ and it will copy files from ../../ and build. 

> Sweet project! When do you feel it's going to be ready for use :-)

Thanks, I'm currently implementing my own protocol for communication between devices and server, that might take quite long time because I'll need to implement that in C because that's only one officially supported language.
